import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Unicorn SaaS',
  description: 'Generated by unicorn productions',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='cupcake' className='scroll-smooth'>
      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
